apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wilayah-indonesia.fullname" . }}
  labels:
    helm.sh/chart: {{ include "wilayah-indonesia.chart" . }}
    app.kubernetes.io/name: {{ include "wilayah-indonesia.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "wilayah-indonesia.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "wilayah-indonesia.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "wilayah-indonesia.serviceAccountName" . }}
      {{- end }}
      imagePullSecrets:
        - name: regcred
      securityContext:
        fsGroup: 2000
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.env.PORT | default 8080 }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: DB_PATH
              value: {{ .Values.env.DB_PATH | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
      nodeSelector:
        kubernetes.io/os: linux